name: docs-deploy

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-deploy.yml'
    branches:
      - main
      - docus-docs

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs/docus
      BASE_URL: /moteus/
    defaults:
      run:
        working-directory: ./docs/docus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name : Cache Packages
        uses: actions/cache@v3
        with:
          path: ${{env.working-directory}}/node_modules
          key: ${{env.working-directory}}/pnpm-lock.yaml

      - name: Generate
        run: pnpm generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.working-directory}}/dist
